# Site settings
course_name: Deep Learning and Computer Vision with PyTorch
course_description: "Deep Learning course with application on Computer Vision, using the PyTorch Library."

baseurl: "/dlcv" # the subpath of your site, e.g. /blog/
url: "http://maurapintor.github.io/dlcv" # the base hostname & protocol for your site

schoolname: "University of Cagliari"
schoolurl: "https://unica.it"
twitter_username: maurapintor 

address: |
    University of Cagliari
    Cagliari
    Italy

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
